spring.application.name=catalog-service

# --- Configuración de Base de Datos (PostgreSQL) ---
# Usamos localhost y puerto 5432 porque es lo que definimos en el docker-compose
spring.datasource.url=jdbc:postgresql://localhost:5432/events_db
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
# --- Configuración de JPA / Hibernate ---
# 'update' creará las tablas automáticamente si no existen (¡Muy útil al empezar!)
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en la consola para saber qué hace JPA por detrás
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# --- Configuración de Eureka ---
# Le decimos dónde está nuestro Discovery Server para que nos encuentre
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# --- Puerto del Servicio ---
server.port=8081